default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: <%= ENV.fetch('DB_USERNAME') { 'username' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'password' } %>

development:
  <<: *default
  database: mirakuru_development

test:
  <<: *default
  database: mirakuru_test

production:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
